name: lint

on:
  workflow_call:
    inputs: {}
  pull_request:
    branches:
      - main
      - v*
      - feature*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.3
      - name: Install go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: 'go.mod'
          # Either this action or golangci-lint needs to disable the cache
          cache: false
      - name: Install mockgen
        run: go install go.uber.org/mock/mockgen@v0.6.0
      - name: Generate mocks
        run: go generate ./...
      - run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
